---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: bazel:app
        ports:
        - name: health
          containerPort: 1234
        livenessProbe:
          tcpSocket:
            port: health
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 1
...